[package]
name = "dionysus"
version = "1.0.0"
edition = "2024"

description = "UI-independent application launcher library"
license = "GPL-3.0-or-later"
repository = "https://github.com/dzavadindev/dionysus"
documentation = "https://github.com/dzavadindev/dionysus/README.md"
homepage = "https://github.com/dzavadindev/dionysus"

keywords = ["launcher", "desktop-entry", "freedesktop", "linux"]
categories = ["command-line-utilities"]

[dependencies]
freedesktop-desktop-entry = "0.8.1"
gtk4 = { version = "0.11.2", features = ["v4_12"] }
notify = "8.2.0"
relm4 = "0.11.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
